M48
; DRILL file {KiCad (6.0.5)} date Wed Sep 30 20:59:00 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T20:59:00+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X98.5Y-83.5
X98.5Y-132.5
X156.5Y-83.5
X186.5Y-83.5
X186.5Y-132.5
T0
M30
